services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2025-CTP2.1-ubuntu-22.04
    ports:
      - "11433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: "Developer"
