services:
  mariadb:
    image: mariadb:10.6.22-ubi9
    restart: no
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "13306:3306"
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"